### ISSUE TITLE
Idea for future video

### ISSUE THREAD

**Issue by vendion** [DiscoverBSD/talks#18]
I wanted to bring this up first before submitting a pull request, but I think this may be an interesting talk to feature.  While it mainly focuses on Minix, the speaker is Andrew Tanenbaum, it talks a bit about both the Minix's kernel space and how the user space is basically NetBSD on top of Minix's mircokernel.

The title of the talk is "A Reimplementation of NetBSD Using a Mircokernel" runtime is ~57:17 and part two of the video can be ignored as it is poorly recorded Q&A.  The video can be found here https://www.youtube.com/watch?v=0pebP891V0c

**Comment by hovancik** [comment]
I like it ;] We can use it for next time (so in 2 weeks)

**Comment by vendion** [comment]
In that case I'll fork the repo and submit a pull request for it later this week if you would like.

**Comment by hovancik** [comment]
Sure thing! And thanks for the contribution.

**Comment by hovancik** [comment]
fixed in https://github.com/DiscoverBSD/talks/pull/19
